### ISSUE TITLE
Cannot set custom color of background rings

### ISSUE THREAD

**Issue by AbirSantra** [k4ds3/react-activity-rings#2]
I want to set the background ring colors to a muted color like shown below. But currently there is no way of doing that.
![image](https://github.com/user-attachments/assets/b510a880-673c-4b05-9ed9-f652c4458808)

**Comment by JonasDoesThings** [comment]
Just released v1.2.0 on npm, see the release changelog on https://github.com/JonasDoesThings/react-activity-rings/releases/tag/v1.2.0 for how to use it
